# Generated by Django 6.0.7 on 2026-08-18 12:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0001_initial'),
        ('organizations', '0001_initial'),
        ('repositories', '0006_repository_organization_alter_repository_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='organizations.organization'),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='repository',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='repositories.repository'),
        ),
        migrations.AddConstraint(
            model_name='invitation',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('organization__isnull', True), ('repository__isnull', False)), models.Q(('organization__isnull', False), ('repository__isnull', True)), _connector='OR'), name='ck_invitation_onto_one_shit'),
        ),
    ]
