# Generated by Django 6.0.7 on 2026-08-18 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='bio',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='display_name',
            field=models.CharField(max_length=100),
        ),
    ]
