# Generated by Django 6.0.7 on 2026-08-04 15:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repositories', '0002_alter_repository_visibility'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='repository',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='unique_user_reponame'),
        ),
    ]
