# Generated by Django 6.0.7 on 2026-08-18 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repositories', '0004_collaborator_invitation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Invitation',
        ),
    ]
