# Generated by Django 6.0.7 on 2026-08-25 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repositories', '0006_repository_organization_alter_repository_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collaborator',
            name='role',
            field=models.CharField(choices=[('READ', 'Read'), ('WRITE', 'Write'), ('ADMIN', 'Admin'), ('OWNER', 'Owner')], default='READ', max_length=5),
        ),
    ]
