# Generated by Django 6.0.7 on 2026-08-19 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orgmember',
            name='visibility',
            field=models.CharField(choices=[('PUBLIC', 'Public'), ('PRIVATE', 'Private')], default='PRIVATE', max_length=7),
        ),
        migrations.AlterField(
            model_name='organization',
            name='display_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
