# Generated by Django 6.0.7 on 2026-08-25 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_orgmember_visibility_alter_organization_display_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orgmember',
            name='role',
            field=models.CharField(choices=[('OWNER', 'Owner'), ('MEMBER', 'Member')], default='MEMBER', max_length=6),
        ),
    ]
