# Generated by Django 6.0.7 on 2026-08-31 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_alter_orgmember_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='default_repo_permission',
            field=models.CharField(choices=[('NONE', 'None'), ('READ', 'Read'), ('WRITE', 'WRITE')], default='NONE', max_length=5),
        ),
    ]
