# Generated by Django 6.0.7 on 2026-09-01 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0004_organization_default_repo_permission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='default_repo_permission',
        ),
    ]
